## Tutorial:
This notebook is designed to walk you through a simple use case of GTEx-Tissue-Classifier. 

### Requirements:
- RNA Sequencing file of sample to test, with Ensembl IDs as row names and TPM values as entries in columns.

In [ ]:
import gtex_tissue_classifier
from gtex_tissue_classifier import architecture, math_logic, real_data, visualization, simulation

ImportError: cannot import name 'architecture' from 'gtex_tissue_classifier' (c:\Python314\Lib\site-packages\gtex_tissue_classifier\__init__.py)

We begin by generating sample input data, both an example RNA sequencing file and a mock GTEx tissue data file. num_genes and num_tissues can be adjusted depending on the desired size of the sample dataset.

In [ ]:
simulation.generate_mock_tissues('sample_gtex.gct', num_genes=100, num_tissues=50)
simulation.generate_mock_sample('sample_tissues.csv', num_genes=100)

Sample tissue matrix created at sample_gtex.gct
Mock sample created and saved to sample_tissues.csv

In [ ]:
gct = real_data.parse_raw_gct('sample_gtex.gct')
real_data.compute_TPM(gct)
gct

,GTEX-0,GTEX-1,GTEX-2,GTEX-3,GTEX-4,GTEX-5,GTEX-6,GTEX-7,GTEX-8,GTEX-9,...,GTEX-41,GTEX-42,GTEX-43,GTEX-44,GTEX-45,GTEX-46,GTEX-47,GTEX-48,GTEX-49,Median_TPM
Name,,,,,,,,,,,,,,,,,,,,,
ENSG000000,0.35199,0.08598,0.62639,0.18251,0.87028,3.50343,0.27910,1.55282,2.57138,0.32932,...,0.61651,0.25397,0.21062,0.35112,0.39787,1.72368,0.13067,0.42746,0.37365,0.313460
ENSG000001,0.81916,0.18420,0.18277,0.70966,0.39039,1.22772,0.26413,0.13610,0.12620,0.45305,...,0.39033,0.17922,0.18635,0.09562,0.60811,1.64821,0.57151,0.26296,0.35203,0.271235
ENSG000002,0.41736,0.38945,0.26520,0.27790,0.20620,0.31249,1.09003,0.24557,0.53163,0.14326,...,0.80659,0.23530,0.40542,0.44619,0.70890,0.53682,0.03757,0.20139,0.26089,0.311880
ENSG000003,0.38777,1.62521,0.85178,0.28920,0.31192,0.12864,0.26141,0.03446,0.03871,0.58068,...,0.51620,0.76048,2.12383,0.29287,4.28511,0.32783,0.22247,0.37131,0.06387,0.353305
ENSG000004,0.67518,0.16969,0.10396,1.04204,0.49637,0.69932,0.35372,0.34596,0.50793,0.25649,...,0.04752,1.32705,0.96315,0.58111,0.54934,0.55991,0.52467,0.95643,0.17650,0.429450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG0000095,0.18511,1.05844,0.04564,0.30115,16.40486,0.41063,0.37961,0.58079,1.89953,0.64782,...,1.12060,0.41507,0.13614,0.01613,0.08812,0.53480,0.20790,0.55306,0.94964,0.412850
ENSG0000096,0.15902,0.70280,0.41992,0.38295,0.26701,0.05755,0.20293,2.48197,1.20864,0.83413,...,0.39232,0.30977,0.33462,0.39747,1.34468,0.55177,0.43353,0.95501,0.31806,0.401195
ENSG0000097,0.28336,1.09528,0.55223,0.90360,0.76173,1.88267,0.45903,0.53651,0.11723,3.08439,...,0.22282,0.20507,0.19408,0.24310,0.55438,0.45416,0.41816,0.06150,0.14372,0.382945
ENSG0000098,1.10852,1.12685,0.20555,1.38073,0.19698,1.05817,0.05377,0.47244,0.61731,0.33672,...,1.06681,0.24246,0.08927,1.50951,0.45790,3.49355,0.40008,0.28160,0.48341,0.449225
ENSG0000099,0.17990,0.32008,1.22210,0.44730,0.33488,0.41600,0.02749,0.32494,0.13263,0.42845,...,0.55916,0.30873,0.30517,0.85416,0.20886,0.08172,1.39178,0.24456,0.05917,0.387715

In [ ]:
sample = architecture.load_input('sample_tissues.csv')
architecture.validate_normalization(sample)
sample

           Gene       TPM
0    ENSG000000  1.646847
1    ENSG000001  0.291437
2    ENSG000002  1.356744
3    ENSG000003  0.107318
4    ENSG000004  0.147882
..          ...       ...
95  ENSG0000095  1.051084
96  ENSG0000096  0.317542
97  ENSG0000097  0.587214
98  ENSG0000098  0.197248
99  ENSG0000099  1.043835

[100 rows x 2 columns]

In [ ]:
corr = math_logic.calculate_spearman(sample, gct)
ranked_tissues = math_logic.rank_matches(corr)
visualization.plot_correlations(ranked_tissues, 'C:\\Users\\jawin\\OneDrive\\Documents\\BIOINF_576\\GTEx-Tissue-Classifier\\tests')