## Tutorial:
This notebook is designed to walk you through a simple use case of GTEx-Tissue-Classifier. 

### Requirements:
- RNA Sequencing file of sample to test, with Ensembl IDs as row names and TPM values as entries in columns.

In [1]:
import gtex_tissue_classifier
from gtex_tissue_classifier import architecture, math_logic, real_data, visualization, simulation

We begin by generating sample input data, both an example RNA sequencing file and a mock GTEx tissue data file. num_genes and num_tissues can be adjusted depending on the desired size of the sample dataset.

In [2]:
simulation.generate_mock_tissues('sample_gtex.gct', num_genes=100, num_tissues=50)
simulation.generate_mock_sample('sample_tissues.csv', num_genes=100)

Sample tissue matrix created at sample_gtex.gct
Mock sample created and saved to sample_tissues.csv

In [3]:
gct = real_data.parse_raw_gct('sample_gtex.gct')
real_data.compute_TPM(gct)
gct

,GTEX-0,GTEX-1,GTEX-2,GTEX-3,GTEX-4,GTEX-5,GTEX-6,GTEX-7,GTEX-8,GTEX-9,...,GTEX-41,GTEX-42,GTEX-43,GTEX-44,GTEX-45,GTEX-46,GTEX-47,GTEX-48,GTEX-49,Median_TPM
Name,,,,,,,,,,,,,,,,,,,,,
ENSG000000,0.20380,2.11251,0.88302,0.53952,0.90467,0.10548,0.40699,0.66081,0.15520,0.09550,...,0.83802,0.89425,0.43743,0.18315,1.83303,0.29177,0.46488,1.51805,1.68926,0.451155
ENSG000001,0.42867,0.39959,0.58675,0.33100,0.64847,0.54411,0.96994,0.65828,0.56115,0.07566,...,0.19840,0.87779,0.23513,0.19461,3.38295,2.30371,0.62420,0.35650,0.41691,0.516395
ENSG000002,0.19632,0.11763,0.53362,0.20093,0.23004,0.44764,1.28039,1.85983,0.04584,0.68995,...,0.33414,1.00461,0.09500,0.23863,1.92846,0.70882,0.37126,0.10524,1.01131,0.392960
ENSG000003,0.41826,0.18203,0.51927,0.71340,0.67157,0.05830,1.01360,0.12606,0.98420,0.09118,...,0.36211,2.33457,0.20942,0.89122,0.12811,0.46079,1.20270,2.71361,0.32514,0.414530
ENSG000004,0.10692,0.14261,0.22710,0.20817,0.17351,0.34847,0.21624,0.42344,0.62611,0.29108,...,0.25918,0.17119,0.02438,0.47110,0.55263,0.65759,0.77978,0.90269,1.61794,0.292010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG0000095,0.66487,0.11107,0.09116,0.12323,0.18783,0.57975,1.95587,0.21983,0.09032,0.29802,...,1.53109,0.16718,2.96747,0.24555,1.65255,0.58250,0.16475,0.83236,0.17755,0.305490
ENSG0000096,0.09493,0.15354,0.93477,0.05614,0.21720,0.34269,0.16394,0.13108,0.08931,0.20674,...,0.16235,0.35819,5.13775,2.08121,0.05836,0.13577,0.37047,0.58628,0.56820,0.279080
ENSG0000097,0.48591,0.55388,0.15193,1.50573,0.27327,0.25445,1.06709,0.54027,0.37896,0.96554,...,0.14158,0.73583,0.05035,0.30375,0.48380,1.99189,0.21944,0.16984,1.38275,0.408460
ENSG0000098,0.46250,0.60206,0.90449,0.39645,0.56933,0.32223,0.33870,0.08331,0.59512,0.16676,...,0.14742,0.39151,1.15095,0.30857,0.63262,0.50181,0.54569,0.36984,0.62800,0.393980
ENSG0000099,0.32343,0.18298,0.51913,1.21090,0.11743,0.65842,0.21146,0.34152,0.04170,0.33385,...,1.03479,0.12025,2.08024,0.10977,0.65965,0.34990,0.89239,0.34413,0.17706,0.347015

In [4]:
sample = architecture.load_input('sample_tissues.csv')
architecture.validate_normalization(sample)
sample

           Gene       TPM
0    ENSG000000  0.294414
1    ENSG000001  0.245479
2    ENSG000002  0.332989
3    ENSG000003  0.519232
4    ENSG000004  0.446934
..          ...       ...
95  ENSG0000095  0.262190
96  ENSG0000096  0.449828
97  ENSG0000097  0.169462
98  ENSG0000098  1.962270
99  ENSG0000099  0.276246

[100 rows x 2 columns]

In [7]:
corr = math_logic.calculate_spearman(sample, gct)
ranked_tissues = math_logic.rank_matches(corr)
visualization.plot_correlations(ranked_tissues, ".") #automatically outputs named png, can specify filepath