## Tutorial:
This notebook is designed to walk you through a simple use case of GTEx-Tissue-Classifier. 

### Requirements:
- RNA Sequencing file of sample to test, with Ensembl IDs as row names and TPM values as entries in columns.

In [6]:
import gtex_tissue_classifier
from gtex_tissue_classifier import architecture, math_logic, real_data, visualization, simulation
from gtex_tissue_classifier.validation import InputValidation

We begin by generating sample input data, both an example RNA sequencing file and a mock GTEx tissue data file. num_genes and num_tissues can be adjusted depending on the desired size of the sample dataset.

In [7]:
simulation.generate_mock_tissues('sample_gtex.gct', num_genes=100, num_tissues=50)
simulation.generate_mock_sample('sample_tissues.csv', num_genes=100)

Sample tissue matrix created at sample_gtex.gct
Mock sample created and saved to sample_tissues.csv

In [8]:
gct = real_data.parse_raw_gct('sample_gtex.gct')
real_data.compute_TPM(gct)
gct

              GTEX-0   GTEX-1   GTEX-2  ...  GTEX-48  GTEX-49  Median_TPM
Name                                    ...
ENSG000000   0.39414  0.74766  1.03962  ...  2.08079  0.53281    0.406335
ENSG000001   0.38743  0.32434  0.60968  ...  0.21408  0.79663    0.393515
ENSG000002   0.24999  0.24001  0.19704  ...  0.54615  0.14422    0.451015
ENSG000003   0.14459  0.27252  0.18069  ...  0.34928  0.14818    0.297095
ENSG000004   0.97299  0.99102  0.13602  ...  1.16757  0.15259    0.525315
...              ...      ...      ...  ...      ...      ...         ...
ENSG0000095  2.16984  0.35347  0.05172  ...  0.02254  1.08677    0.347415
ENSG0000096  0.98332  0.09234  0.20909  ...  0.58486  0.29294    0.322655
ENSG0000097  1.78586  0.66128  0.05357  ...  0.36667  0.24167    0.535285
ENSG0000098  0.20570  0.42422  0.67111  ...  0.72592  2.60478    0.400605
ENSG0000099  0.69617  1.32711  0.50850  ...  0.33871  0.29276    0.480130

[100 rows x 51 columns]

In [9]:
sample = architecture.load_input('sample_tissues.csv')
validator = InputValidation(sample, gct)
sample = validator.run_all_validations()
sample

           Gene       TPM
0    ENSG000000  0.745360
1    ENSG000001  0.179731
2    ENSG000002  0.745843
3    ENSG000003  0.422376
4    ENSG000004  0.343085
..          ...       ...
95  ENSG0000095  0.354193
96  ENSG0000096  0.549967
97  ENSG0000097  0.385978
98  ENSG0000098  0.362802
99  ENSG0000099  0.331042

[100 rows x 2 columns]

In [10]:
corr = math_logic.calculate_spearman(sample, gct)
ranked_tissues = math_logic.rank_matches(corr)
visualization.plot_correlations(ranked_tissues, ".") #automatically outputs named png, can specify filepath